id = "fluent"
name = "Fluent"
version = "0.13.0"
schema_version = 1
authors = ["Saeid Ghafari <saeid.sran@gmail.com>"]
description = "Zed Extension for fluent"
repository = "https://github.com/YouKnow-sys/fluent-zed"

[grammars.fluent]
repository = "https://github.com/YouKnow-sys/tree-sitter-fluent"
commit = "13fc06c7b3d4352095c7831255427f76306aa65c"
