name = "Fluent"
grammar = "fluent"
path_suffixes = ["ftl"]
autoclose_before = ",=)}]\n"
line_comments = ["# "]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false }
]
